# Sample .travis.yml for R projects

language: r
warnings_are_errors: true
sudo: required

r_packages:
  - rmarkdown
  - devtools

r_github_packages:
  - caseywdunn/hutan

bioc_packages:
  - edgeR
  -DESeq2